README.Rmd
vignettes/germany-age-stratified-nowcasting.Rmd
vignettes/model.Rmd

I've just fixed a few typos in the documentation (README and vignettes). 
Thank you very much for the development of this very useful package!

Fixed a few typos in the documentation

---

R/postprocess.R

This PR drops `na.rm` requirement from some posterior package

Bug: drop na.rm requirement for posterior functions

---

vignettes/germany-age-stratified-nowcasting.Rmd
vignettes/germany-age-stratified-nowcasting.Rmd.orig
vignettes/model.Rmd

This PR adds changes based on recent comments from @sbfnk. These changes are:
- Update the hazard to probabiltiy and probability to hazard equations to use improved notation
- Adding text explaining the use of `enw_preprocess_data()`
- Adding text giving more context for the posterior plots
- Adding additional text highlighting that the approximate leave one out information criterion is not a principled measure for this use case and providing a link out to the approximate leave future out cross validation vignette. 
- Adding text to explain the logit hazard step in more detail and to clarify the statement that the final hazard is 1.

Feature: @sbfnk comments

---

DESCRIPTION
NEWS.md
R/postprocess.R

This PR fixes a bug which led to duplicated summarised samples when samples were summarised manually vs using `cmdstanr`.

Bug: Fix presence of duplicate summarise samples

---

DESCRIPTION

Since we added code optimization with stanc, we require CmdStan 2.29 at least.

Update CmdStan version

---

DESCRIPTION
NEWS.md
inst/stan/functions/hazard.stan

This PR makes use of ideas from @adrian-lison and implemented [here](https://github.com/adrian-lison/nowcast-transmission/blob/main/code/models/functions/helper_functions.stan) to vectorise `hazard_to_prob`. It differs from this implementation in two ways. Firstly it does not assume the complete hazard is available (due to this not being the case in the likelihood call) and therefore does not optimise the probability at the maximum delay. Secondly, it makes use of `log1m` for a slight performance boost and numerical stability. 
It also adds slight optimisations to `prob_to_hazard` so that only required cumulative probabilities are calculated. 
Initial testing suggests this gives a small speedup at the cost of slightly less clear code.

Vectorise hazard_to_prob

---

NEWS.md
R/model-modules.R
inst/stan/epinowcast.stan
inst/stan/functions/discretised_reporting_prob.stan
man/enw_reference.Rd
tests/testthat/test-enw_reference.R

This PR adds the loglogistic distribution as a fourth option for the parametric delay distribution. It is similar to the lognormal (slightly heavier tails), and often used in survival modeling due to its closed-form solution for the hazard function. I have managed to work out the closed-form solution for the discrete hazard case, so this will be another parametric function (aside from the exponential) that we can efficiently implement on the hazard scale (i.e. using vectorized, simple computations only). Can work on this after this PR is merged.

Add loglogistic parametric distribution

---

NEWS.md
R/model-modules.R
inst/stan/epinowcast.stan
tests/testthat/test-enw_reference.R
tests/testthat/test-enw_report.R

This PR fixes #141 by correctly setting `ref_as_p` based on `model_rep` and `model_refp` as passed by `enw_report()` and `enw_reference()`. It also adds additional tests to cover this issue in the future. 
It replicates the fix added in #140 and replaces it.

Bug: ref_as_p not activating

---

NEWS.md
R/formula-tools.R
man/enw_formula.Rd
tests/testthat/_snaps/enw_formula.md
tests/testthat/test-enw_formula.R

This PR adds support for interactions on the right-hand side of random effects (i.e `(1 + month | day_of_week:age_group)`. This should result in a model with an independent random effect for each age group on the day of the week and random slopes on the month drawn from separate hyper distributions for each age group.
This feature is motivated by #152 where we need to be able to specify independent random effects for each group easily in order to reproduce the current default model. There may also be other use cases in the future. 
Potentially this syntax is not ideal and/or there are other work around to this feature that I am not aware of. 
I have added: 
- Functionality to support random effect interactions
- An example in the documentation of `enw_formula` showcasing this …

Feature: interactions in random effects

---

NEWS.md
R/model-tools.R
man/enw_model.Rd
man/epinowcast.Rd

This PR adds support for passing `cpp_options` this is useful for example when using GPU support (testing this out indicates it doesn't help on small scale models and in fact leads to a large slow down).

Feature cpp options

---

NEWS.md
R/model-tools.R
man/enw_model.Rd

This PR adds the ability to pass the `target_dir` argument from `write_stan_files_no_profile` from `enw_model`. This is helpful when using the model in multiple R sessions and wanting to share a single compiled file.

Add target dir passing to enw_model

---

DESCRIPTION
NEWS.md
R/epinowcast.R
R/preprocess.R
man/epinowcast.Rd
tests/testthat/test-enw_delay_filter.R
tests/testthat/test-epinowcast.R

This PR closes #167 by adding a warning when the maximum empirical delay is shorter than the specified maximum delay. It also adds unit tests for `enw_delay_filter` and adds a unit test to check that `epinowcast` fits as expected using its default settings (this catches a bug in the settings for `enw_fit_opts` that was caught whilst developing this PR.

Added a warning about empirical and specified delay being different

---

NEWS.md
R/utils.R

Updates `convert_cmdstan_to_rstan` to deal with some previously unsupported array notation. 
This may address the issue mentioned in https://github.com/epinowcast/epinowcast/issues/174#issuecomment-1356889203.

compatibility with additional array notation

---

DESCRIPTION
NEWS.md
R/model-validation.R

This PR closes #198 by forcing the conversion of `true_value` and `prediction` as indicated by @nikosbosse (the author of `scoringutils`) as the likely fix. 
It also increments the dev version and adds a news item (the review might consider adding a reviewed by tag to this once their review is complete). 
The following code now works as expected and package tests are passing. 
```r
library(epinowcast)
nowcast <- enw_example("nowcast")
summarised_nowcast <- summary(nowcast)
obs <- enw_example("observations")
enw_score_nowcast(summarised_nowcast, obs)
```

Force numeric for prediction and true value when scoring

---

NEWS.md
R/check.R
R/plot.R
tests/testthat/test-check_by.R
tests/testthat/test-check_modules_compatible.R
tests/testthat/test-check_quantiles.R

This PR increases test coverage by adding unit tests for `check_` functions where missing. In adding these tests I noticed that `check_quantiles` was not as flexible as originally intended so I have refactored. 
I have also removed two internal plot functions that were not be used and were untested.

Add unit tests for check_ functions and remove internal plots

---

DESCRIPTION
NEWS.md
R/formula-tools.R
R/model-design-tools.R
man/enw_add_pooling_effect.Rd
tests/testthat/test-enw_add_pooling_effect.R

still need some other `finder_fn` examples to add to testing?

draft change: add_pooling_effect to more generic finder_fn

---

.github/workflows/lint-changed-files.yaml

Since this workflow is set up to run on files modified in a PR, it doesn't make sense to have it run in pushes (and it will fail). It's not an issue since all changes are done via PR so you are sure that this workflow will still always run on new code.

Disable lint workflow on pushes

---

DESCRIPTION

This PR adds @Bisaloo as a package author and @pratikunterwegs as a contributor and reorders the DESCRIPTION to go authors and then contributors. I may have missed people who should be credited here so please make suggestions.
@Bisaloo and @pratikunterwegs if you could both confirm you are fine to be added here that would be great.

Add @bisaloo as an author and @pratikunterwegs as a contributor

---

DESCRIPTION
NEWS.md
R/preprocess.R
man/enw_metadata.Rd
man/epinowcast-package.Rd
tests/testthat/test-enw_metadata.R

This PR closes #212 by detecting the defaults for `target_date` from the function specification using `formals()`.

`enw_metadata()` `target_date` default be detected from the function specification

---

DESCRIPTION
NEWS.md
R/check.R
R/preprocess.R

In the words of Jenny Bryan: "there is no else, there is only if."
https://speakerdeck.com/jennybc/code-smells-and-feels?slide=45
Having `else` after `return()` of `stop()` increases the number of branches in the code, which makes it harder to read. It also translates into a higher cyclomatic complexity.

Do not use else after stop()

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/model-modules.R

This PR closes #273.
In this PR I have tightend the passing of arrays to stan in order to work with the latest version of `cmdstan` (`2.32.1`). I have also increment the package into a dev version and created a new dev version news item.

Issue 273: Use array syntax for initial conditions in order to work with cmdstan 2.32.1

---

DESCRIPTION
NEWS.md
vignettes/distributions.Rmd

This PR closes #278 
Some minor changes to the discrete delay distributions vignette - escaping functions to improve readibility and right-closing discretised bins.
Seems to small to be worthy of a news item.

Issue 278: minor improvements to the discrete delay distributions vignette

---

DESCRIPTION
NEWS.md

As #273 means that the current release is broken with the latest `cmstan` release I think we should have a small patch release.
It doesn't really need to be reviewed I think as its so minor but do say if you have views (or think it should be reviewed). If no issues will update to a release version, merge this in, and make a GitHub release tomorrow.
Tagging @epinowcast/developers

0.2.2 release

---

NEWS.md
README.Rmd

This PR closes #272.
As discussed in #272 the citation command was not shown to users in the README. This PR fixes that. It also changes the output from `citation("epinowcast")` from a comment into normal text.

Issue 272: Make citation command print prettily

---

NEWS.md
vignettes/distributions.Rmd
vignettes/germany-age-stratified-nowcasting.Rmd
vignettes/germany-age-stratified-nowcasting.Rmd.orig
vignettes/model.Rmd
vignettes/single-timeseries-rt-estimation.Rmd
vignettes/single-timeseries-rt-estimation.Rmd.orig
vignettes/stan-help.Rmd

This PR closes #415. It drops individuals from all vignettes and instead includes a team authorship. As `pgdown` automatically includes a link to the `vignette` source I have not added a manual link out to this as discussed in #415. 
Could reviewers please suggest their usernames in the news item as reviewers. Note that all tagged reviewers don't need to review this as we have already discussed and agreed these changes in #415 so tagging is just for visibility.
[Describe the changes that you made in this pull request.]

Issue 415: Change all vignette authorship to be epinowcast team vs individuals

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/model-modules.R
R/utils.R
README.md
man/coerce_date.Rd
tests/testthat/helper-expectations.R
tests/testthat/helper-functions.R
tests/testthat/helper-state.R
tests/testthat/test-coerce_date.R
tests/testthat/test-enw_preprocess_data.R
tests/testthat/test-enw_reference.R
tests/testthat/test-epinowcast.R

This PR closes #389  (maybe...).
Replaces post R4.1.0 anonymous function syntax (`\(x)`) and native pipe (`|>`) from the source and test files.
Does not remove or notify the users that R >= 4.1.0 is necessary for running or rebuilding the vignettes.
This will at least guarantee that the package will build and test on platforms with R >= 3.5.

Issue 389: minimum supported R version 3.5 or 4.1

---

.github/actions/touchstone-recieve/action.yaml
.github/workflows/R-CMD-check.yaml
.github/workflows/check-cmdstan.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

This PR switches all actions to use the new `epinowcast/actions/install-cmdstan` action which comes with the addition of caching (and hence should slightly speed up CI). 
Note that there is an upstream issues with `cmdstanr` on windows platforms that is causing all windows CI to fail.
@sbfnk tagged due to similar work in `EpiNow2` but also might be of interest to @Bisaloo.

Issue 436: Switch to epinowcast/actions/install-cmdstan

---

NEWS.md
inst/stan/functions/discretised_logit_hazard.stan

This PR should close #302 by further improving the doxygen comments for the stan code in `discretised_logit_hazard.stan`.
The current doc mostly used the number of values/elements `n` in the various vectors for hazards, log-probabilities and cdfs. This was easy because they all have the same length, but failed to point out the differences in indexing between probabilities and cdfs. It also did not make clear the connection to the maximum delay assumption and the truncation that we apply to the distributions.
I now changed the documentation and interface of the internal functions to use an upper bound `u` instead of the number of elements `n`. This does not change anything semantically, as `n=u` in all cases currently supported by epinowcast. However, I find this more inuitive, as it …

Issue 302: Improve commenting of maximum delay in Stan code

---

.github/workflows/test-coverage.yaml

Work from @sbfnk  in [#EpiNow2/](https://github.com/epiforecasts/EpiNow2/pull/722) suggests this may be faster.

Switch to macOS for coverage action 

---

NEWS.md
inst/stan/functions/expected_obs.stan
inst/stan/functions/expected_obs_from.stan
tests/testthat/test-stan_expected_obs.R

This PR closes #481. It adds an indicator (`agg_probs`) and a matrix argument (`agg_indicator`) to `expected_obs()` that indicate whether to aggregate and how the aggregation should be performed, respectively. The matrix argument is structured to be directly multiplied to the probability vector: the rows represent which index the aggregated probability should be placed on in the new probability vector that accounts for the reporting cycle, and the columns represent whether a given probability in the probability vector should be aggregated. For example, if we had the aggregation matrix 
```math
\texttt{agg}\_\texttt{indicator} = \begin{bmatrix} 0 & 0 & 0 & 0 & 0 & 0 \\\ 0 & 0 & 0 & 0 & 0 & 0 \\\ 1 & 1 & 1 & 0 & 0 & 0 \\\ 0 & 0 & 0 & 0 & 0 & 0 \\\ 0 & 0 & 0 & 0 & 0 & 0 \\\ 0 & 0 & 0 & 1 & 1 …
```

Issue #481: Add support for probability aggregation to `expected_obs()`
