epinowcast/epinowcast

DESCRIPTION
NEWS.md
R/model-validation.R
README.Rmd
man/enw_score_nowcast.Rd

This PR adds optional log scoring and updates the news section.

Feature: Add log scoring

---

DESCRIPTION

Adding myself as a contributor. Thanks @seabbs !

add michael dewitt as a contributor

---

DESCRIPTION

Add Adrian Lison as contributor

---

.Rbuildignore
.gitignore
R/model.R
inst/stan/epinowcast.stan

This PR fixes #44. In addition, it makes the regex for the optional profiling white-space independent.

Bugfix optional profiling

---

.github/workflows/R-CMD-check.yaml

Update R-CMD-check.yaml to support current Rtools requirements

---

NEWS.md
inst/stan/epinowcast.stan

This PR adds support for `inv_sqrt` (https://mc-stan.org/docs/2_18/functions-reference/power-and-logarithm-functions.html. No change in output or performance impact.

Add inv_sqrt

---

.Rbuildignore
CONTRIBUTING.md
README.Rmd
README.md

This PR adds a contributing guide adapted from https://github.com/ropensci/jagstargets

Feature contributing

---

CONTRIBUTING.md

This PR closes #73 by updating the contributing document to reflect current package workflow.

Update contributing to include use of develop branch system

---

NEWS.md
R/utils.R
tests/testthat/test-convert_cmdstan_to_rstan.R

Safer regex as suggested by @sbfnk here: https://github.com/epiforecasts/epinowcast/pull/85#discussion_r913227210

Bug safer regex

---

NEWS.md
R/formula-tools.R
R/model-tools.R

As recommended in https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/

Use inherits to test class

---

NEWS.md
R/formula-tools.R
R/methods.R
R/model-modules.R
R/preprocess.R
man/enw_fit_opts.Rd
man/enw_metadata.Rd
man/enw_obs.Rd
man/enw_reference.Rd
man/plot.epinowcast.Rd
man/rw.Rd
man/summary.epinowcast.Rd

Addresses #156, with the exception of some esoteric `match.arg` uses

address match.args change

---

.gitignore
NEWS.md
vignettes/library.bib
vignettes/model.Rmd

This work in progress PR adds the renewal equation generative process and the latent reporting convolution to the model overview vignette.

Add renewal and latent reporting to model overview

---

R/plot.R
inst/examples/germany_latent_renewal.R
inst/examples/germany_missing.R
vignettes/germany-age-stratified-nowcasting.Rmd
vignettes/germany-age-stratified-nowcasting.Rmd.orig

This PR is a repeat of #197 which was spuriously targeted at `main`. No other changes have been made so it likely does not need to reviewed again. Tagging @adrian-lison as the reviewer on the previous PR.

Fix linewidth in ggplot2

---

DESCRIPTION

As per #225 and @pearsonca comment this PR fixes usage of `c()`.

Standardise use of c() for DESCRIPTION

---

DESCRIPTION
NEWS.md
R/model-tools.R

This PR closes #245.
Cleaning enw_formula_as_data_list() in R/model-tools.R to align with DRY principles. Also added @Lnrivas as a contributor in DESCRIPTION and described changes in NEWS.md

 Issue 245: Cleaning enw_formula_as_data_list() to align with DRY principles (#245)

---

DESCRIPTION
NEWS.md
vignettes/model.Rmd

This PR closes #291 
Fix some typos in the "model.Rmd" vignette.

Issue 291: Typos in model.Rmd

---

.github/workflows/R-CMD-as-cran-check.yaml
.github/workflows/R-CMD-check.yaml
.github/workflows/lint-changed-files.yaml
.github/workflows/test-coverage.yaml
NEWS.md

This PR closes #298 by adding `merge_group` to all required GitHub Actions. This enables the use of a merge queue that triggers all our required checks automatically.

Issuee 298: Add merge_group for required GitHub Actions to enable the use of a merge queue.

---

DESCRIPTION
NEWS.md
tests/testthat/helper-state.R

This PR closes #331.
I believe these two changes are small enough to be a single PR and I have ensured they are done in distinct commits. But please let me know if you'd prefer I open two PR.

Issue 331: Add partial matching & global state checks in testthat checks

---

.github/dependabot.yml

This PR adds `dependabot` to manage GitHub Action versions.

Add dependabot for managing GitHub Actions

---

NEWS.md

This PR closes #373.
The word "error" is replaced by "warning" to align with the changes in the linked PR of the NEWs item.

Issue 373: Fix NEWS item

---

README.Rmd
README.md

This PR closes #<issue-number>.
[Describe the changes that you made in this pull request.]

Hotfix: Logo in readme placement

---

.github/PULL_REQUEST_TEMPLATE.md
NEWS.md

This PR closes #299.
It removes the request in the PR template for contributors to increment the development version.
Tagged @Bisaloo to review as most active in #299.

Issue 299: Stop asking contributors to increment the development version

---

vignettes/stan-help.Rmd

This PR resolves some of the typos in https://github.com/epinowcast/epinowcast/commit/ffd013b56f90657d4c412024e6b94fea049ec6c8
Fixed some whitespace issues and typos.
- [ x] I have reviewed CI checks for this PR and addressed them as far as I am able.

Hotfix: update some stan typos

---

DESCRIPTION

I missed this on #405 but I think @medewitt is over the bar for authorship. @medewitt okay with you?

Move @medewitt  to author

---

tests/testthat/_snaps/enw_plot_obs/enw-plot-obs-default-with-log-scale.svg
tests/testthat/_snaps/enw_plot_obs/enw-plot-obs-default.svg
tests/testthat/_snaps/plot.epinowcast/plot-epinowcast-posterior-predictions.svg

As the title this PR closes #443 by updating the snapshots using the latest version of `ggplot2`. I have tested this locally.
@pearsonca or @adrian-lison want to review?

Issue 443: Fix snapshots due to latest ggplot2

---

.github/workflows/contributors.yaml
README.Rmd
README.md

This PR closes #444.
It uses the `allcontributors` R package to maintain a section in the README - I chose the "text" format to minimise clutter but other options are available - see [examples](https://docs.ropensci.org/allcontributors/articles/allcontributors.html).

444: Add contributors workflow

---

NEWS.md
_pkgdown.yml
inst/WORDLIST

This PR closes #448. Specifically the part stating:
> There are also some broken links when trying to search for terms.

Issue 448: Fix pkgdown site URL

---

DESCRIPTION
_pkgdown.yml

Issue 457: Standardise function group punctuation

---

NEWS.md

This PR closes #<issue-number>.
[Describe the changes that you made in this pull request.]

Add development release to news

---

R/model-design-tools.R
R/model-modules.R
R/model-tools.R
R/utils.R
tests/testthat.R
tests/testthat/helper-state.R
tests/testthat/setup-options.R
tests/testthat/test-enw_expectation.R
tests/testthat/test-enw_missing.R
tests/testthat/test-enw_obs.R
tests/testthat/test-enw_quantiles_to_long.R
tests/testthat/test-enw_reference.R
tests/testthat/test-enw_report.R
tests/testthat/test-enw_stan_to_r.R
tests/testthat/test-epinowcast.R

Follow up of #338 
This PR is opened as a draft because checks are expected to fail. There are instances of partial matching in abind and since this package is not hosted on a public git repo, I can't submit a PR.
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L68
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L105
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L118
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L149
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L195
https://github.com/cran/abind/blob/7d7185af7c3b3c487be6dcd2a4a69224d596ff0a/R/abind.R#L204 …

Issue 331: Add partial matching options to setup-options

---

NEWS.md
inst/stan/functions/expected_obs.stan

This PR closes #487 by fixing the use of a depreciated function. 
@jessalynnsebastian I pinged you for review as this is related to #482 but if no time then please unrequest yourself and I will flag another contributor!

Issue 487: Fixed use of enw_expose_stan_fns

---

.github/workflows/render-stan-docs.yaml

Adds suggested GH features from #500.

Customise stan docs GH

---

DESCRIPTION

Based on contributions to issues (#427, #483), PRs (#482), and review (#501). @jessalynnsebastian happy with this?

Move JS to author

---

DESCRIPTION
NEWS.md
_pkgdown.yml
inst/WORDLIST
vignettes/package-use-cases.Rmd

This PR closes #96 
This PR creates a vignette with a markdown table to document package use cases. It's intended as a starting point for others to contribute to when they use `{epinowcast}` for a real world application (whether for research or response), organized into a standardized format to track project description, pathogen, data type, purpose, location, organization type, and links. 
Open to any and all suggestions here to make this more concise (e.g. perhaps we don't need the separate location for geographic granularity of data if this can be described succinctly in data type(s) or description).

Issue 96: Create vignette documenting package use cases

---

NEWS.md
_pkgdown.yml

This PR partially closes #503.
[Describe the changes that you made in this pull request.]
This PR restructures the pkgdown yml configuration and links the Stan documentation.

Issue #503 - Link Stan function reference to pkgdown
